services:
    php-fpm:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: true
        ports:
            - "${APP_PORT}:8080"
        depends_on:
            - postgres
        volumes:
            - .:/var/www
            - ./logs:/var/www/logs
            - ./.docker/php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - document-sharing-network
        extra_hosts:
            - host.docker.internal:host-gateway
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - document-sharing-db:/var/lib/postgresql/data
        networks:
            - document-sharing-network
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - document-sharing-network

volumes:
    logs:
        driver: local
    document-sharing-db:
        driver: local

networks:
  document-sharing-network:
    driver: bridge
