services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: true
        ports:
            - "${APP_PORT}:8080"
        depends_on:
            - postgres
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - app-network
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        depends_on:
            - php-fpm
        networks:
            - app-network
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - document-sharing-db:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    logs:
        driver: local
    document-sharing-db:
        driver: local

networks:
  app-network:
    driver: bridge
